project_id = "msdtuhrfehnexfwnboyd"

[functions.create-checkout]
verify_jwt = false

[functions.verify-session]
verify_jwt = false

[functions.compare-exams]
verify_jwt = false

[functions.create-test-user]
verify_jwt = false

[functions.visual-analyze]
verify_jwt = true

[functions.manage-user]
verify_jwt = false
